package DNS_RR_Types is
-- IANA Registered RRTypes
   type RR_Types is
     (A,
      NS,
      MD,
      MF,
      CNAME,
      SOA,
      MB,
      MG,
      MR,
      DNS_NULL,
      WKS,
      PTR,
      HINFO,
      MINFO,
      MX,
      TXT,
      RP,
      AFSDB,
      X25,
      ISDN,
      RT,
      NSAP,
      NSAP_PTR,
      SIG,
      KEY,
      PX,
      GPOS,
      AAAA,
      LOC,
      NXT,
      EID,
      NIMLOC,
      SRV,
      ATMA,
      NAPTR,
      KX,
      CERT,
      A6,
      DNAME,
      SINK,
      OPT,
      APL,
      DS,
      SSHFP,
      IPSECKEY,
      RRSIG,
      NSEC,
      DNSKEY,
      DHCID,
      NSEC3,
      NSEC3PARAM,
      TLSA,
      SMIMEA,
      HIP,
      NINFO,
      RKEY,
      TALINK,
      CDS,
      CDNSKEY,
      OPENPGPKEY,
      CSYNC,
      SPF,
      UINFO,
      UID,
      GID,
      UNSPEC,
      NID,
      L32,
      L64,
      LP,
      EUI48,
      EUI64,
      TKEY,
      TSIG,
      IXFR,
      AXFR,
      MAILB,
      MAILA,
      WILDCARD,
      URI,
      CAA,
      AVC,
      DOA,
      TA,
      DLV);
   for RR_Types use
     (A          => 1,
      NS         => 2,
      MD         => 3,
      MF         => 4,
      CNAME      => 5,
      SOA        => 6,
      MB         => 7,
      MG         => 8,
      MR         => 9,
      DNS_NULL   => 10,
      WKS        => 11,
      PTR        => 12,
      HINFO      => 13,
      MINFO      => 14,
      MX         => 15,
      TXT        => 16,
      RP         => 17,
      AFSDB      => 18,
      X25        => 19,
      ISDN       => 20,
      RT         => 21,
      NSAP       => 22,
      NSAP_PTR   => 23,
      SIG        => 24,
      KEY        => 25,
      PX         => 26,
      GPOS       => 27,
      AAAA       => 28,
      LOC        => 29,
      NXT        => 30,
      EID        => 31,
      NIMLOC     => 32,
      SRV        => 33,
      ATMA       => 34,
      NAPTR      => 35,
      KX         => 36,
      CERT       => 37,
      A6         => 38,
      DNAME      => 39,
      SINK       => 40,
      OPT        => 41,
      APL        => 42,
      DS         => 43,
      SSHFP      => 44,
      IPSECKEY   => 45,
      RRSIG      => 46,
      NSEC       => 47,
      DNSKEY     => 48,
      DHCID      => 49,
      NSEC3      => 50,
      NSEC3PARAM => 51,
      TLSA       => 52,
      SMIMEA     => 53,
      HIP        => 55,
      NINFO      => 56,
      RKEY       => 57,
      TALINK     => 58,
      CDS        => 59,
      CDNSKEY    => 60,
      OPENPGPKEY => 61,
      CSYNC      => 62,
      SPF        => 99,
      UINFO      => 100,
      UID        => 101,
      GID        => 102,
      UNSPEC     => 103,
      NID        => 104,
      L32        => 105,
      L64        => 106,
      LP         => 107,
      EUI48      => 108,
      EUI64      => 109,
      TKEY       => 249,
      TSIG       => 250,
      IXFR       => 251,
      AXFR       => 252,
      MAILB      => 253,
      MAILA      => 254,
      WILDCARD   => 255,
      URI        => 256,
      CAA        => 257,
      AVC        => 258,
      DOA        => 259,
      TA         => 32768,
      DLV        => 32769);

   function To_String(RR_Type : RR_Types) return String;

end DNS_RR_Types;
